// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcmqVzSUkSH6aT5jd_Hcn-iTmNYD1pD5A',
    appId: '1:748897435275:web:edc9af1efdefc9ebcfde8e',
    messagingSenderId: '748897435275',
    projectId: 'employee-attendance-syst-a7158',
    authDomain: 'employee-attendance-syst-a7158.firebaseapp.com',
    storageBucket: 'employee-attendance-syst-a7158.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_nNHgfRnSSBZfRDbuuCmQE9pW-Ykh0iQ',
    appId: '1:748897435275:android:00f28eb2b6c24e6ccfde8e',
    messagingSenderId: '748897435275',
    projectId: 'employee-attendance-syst-a7158',
    storageBucket: 'employee-attendance-syst-a7158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUWO7l2qDrO2BSnwydXiLB64zZO_jrGFs',
    appId: '1:748897435275:ios:1e9d65168529cac4cfde8e',
    messagingSenderId: '748897435275',
    projectId: 'employee-attendance-syst-a7158',
    storageBucket: 'employee-attendance-syst-a7158.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUWO7l2qDrO2BSnwydXiLB64zZO_jrGFs',
    appId: '1:748897435275:ios:1e9d65168529cac4cfde8e',
    messagingSenderId: '748897435275',
    projectId: 'employee-attendance-syst-a7158',
    storageBucket: 'employee-attendance-syst-a7158.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcmqVzSUkSH6aT5jd_Hcn-iTmNYD1pD5A',
    appId: '1:748897435275:web:a2f043fef14a608acfde8e',
    messagingSenderId: '748897435275',
    projectId: 'employee-attendance-syst-a7158',
    authDomain: 'employee-attendance-syst-a7158.firebaseapp.com',
    storageBucket: 'employee-attendance-syst-a7158.firebasestorage.app',
  );
}
